### ISSUE TITLE
Our app crashes on load when building with Xcode 12.4 and latest version 1.1.5

### ISSUE THREAD

**Issue by msquitieri** [acquireio/AcquireIOSupport-Lite#1]
Our React Native app immediately crashes after upgrading to version 1.1.5. The build completes successfully, but when you open the app, it immediately crashes.

We did not have this issue with version 1.1.4.

Building the app with Xcode 12.5.1 seems to work. Is this a new requirement? We would prefer to be able to build with Xcode 12.4 since that is the latest version that our AppCenter builds allows.

Thanks!

**Comment by Chirag-Acquire** [comment]
Please confirm below post-installation steps in your podfile.


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['TwilioVideo', 'Socket.IO-Client-Swift', 'Starscream'].include? target.name
      target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end

**Comment by msquitieri** [comment]
We are no longer using your service, so I'm going to go ahead and close this.
